### Pytorch 实践 Day1 tensor 的操作


In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
! nvidia-smi

Fri Oct 21 07:29:48 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [4]:
import torch

Chunk 函数的使用, 将tensor进行切分， 参数有(待切分的tensor, 切分的部分数,以及切分的维度, 默认是1)

In [5]:
b = torch.rand([3,2,]) #定义随机张量

In [6]:
b

tensor([[0.2545, 0.3309],
        [0.7188, 0.3467],
        [0.9534, 0.1721]])

In [9]:
torch.chunk(b, chunks=2, dim=0) #沿着第一个维度进行切分

(tensor([[0.2545, 0.3309],
         [0.7188, 0.3467]]), tensor([[0.9534, 0.1721]]))

In [10]:
torch.chunk(b, chunks=2, dim=1)

(tensor([[0.2545],
         [0.7188],
         [0.9534]]), tensor([[0.3309],
         [0.3467],
         [0.1721]]))

In [11]:
c,d = torch.chunk(b, chunks=2, dim=1)

In [12]:
c

tensor([[0.2545],
        [0.7188],
        [0.9534]])

In [13]:
d

tensor([[0.3309],
        [0.3467],
        [0.1721]])

###Gather 函数

Gather函数主要是利用已有的矩阵生成未知的矩阵.
函数的要传入的参数主要有(input, dim, index)

input是一个要输入的矩阵, 

dim是输入的维度, 输入那个维度, 就给相应的维度所在的索引进行一个改变。而保持其他维度不变

index就是索引值

In [15]:
# Example

t = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
new = torch.gather(t, 1, torch.tensor([[0,2,1],[1,0,2],[2,2,2]]))

In [16]:
new

tensor([[1, 3, 2],
        [5, 4, 6],
        [9, 9, 9]])

### Reshape 函数

In [17]:
b = torch.tensor([[0, 1], [2, 3]])

In [27]:
torch.reshape(torch.reshape(b, (4,-1)),(-1,))

tensor([0, 1, 2, 3])

### Scatter 函数

In [28]:
src = torch.arange(1,16).reshape((3,5))

In [29]:
src

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])

In [65]:
index = torch.tensor([[0, 1, 2, 0, 0],[1,2,1,1,1]])
#将index的除了第dim维其他均保持不变, 将dim维改为索引 index

In [32]:
torch.zeros(3,5, dtype=src.dtype).scatter_(0, index,src)

tensor([[ 1,  0,  0,  4,  5],
        [ 6,  2,  8,  9, 10],
        [ 0,  7,  3,  0,  0]])

In [66]:
src = 1
index = torch.tensor([[1],[0]])

In [68]:
index = torch.tensor([[1], [2], [0], [3]])
onehot = torch.zeros(4, 4)
onehot.scatter_(1, index, 1)
print(onehot)

tensor([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.]])


## Split函数

In [75]:
a = torch.tensor([[1,2],[3,4],[4,5]])

In [78]:
torch.split(a,[1,2],dim=0) #split 函数将tensor划分为不同的堆

(tensor([[1, 2]]), tensor([[3, 4],
         [4, 5]]))

### Squeeze函数

In [81]:
c = torch.tensor([[[1],[2],[3],[4]]]) #将维数为1的维压缩掉

In [82]:
torch.squeeze(c)

tensor([1, 2, 3, 4])

In [84]:
c =  torch.reshape(torch.arange(12),(3,1,1,4))

In [85]:
c

tensor([[[[ 0,  1,  2,  3]]],


        [[[ 4,  5,  6,  7]]],


        [[[ 8,  9, 10, 11]]]])

In [87]:
torch.squeeze(c)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [88]:
## squeeze不能传入列表

In [89]:
c =  torch.reshape(torch.arange(12),(3,1,1,4))


In [90]:
torch.squeeze(c, dim=1)

tensor([[[ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11]]])

torch.stack函数, 将两个torch堆叠起来

In [109]:
a=torch.tensor([[1,2],[3,4],[8,9]])
b=torch.tensor([[4,5],[6,7],[10,11]])
torch.stack([a,b], dim=0)

tensor([[[ 1,  2],
         [ 3,  4],
         [ 8,  9]],

        [[ 4,  5],
         [ 6,  7],
         [10, 11]]])